name: deno-test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
      - name: deno test
        run: |
          deno test
